version: "3"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./public:/var/www/laravelSample/public
    depends_on:
      - phpfpm
  phpfpm:
    build: .
    volumes:
      - .:/var/www/laravelSample
    environment:
      DB_HOST: mysql
      DB_DATABASE: laravelSample_db
      DB_USERNAME: laravelSample
      DB_PASSWORD: laravelSample
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: laravelSample
      MYSQL_DATABASE: laravelSample_db
      MYSQL_USER: laravelSample
      MYSQL_PASSWORD: laravelSample
      TZ: 'Azia/Tokyo'
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    command: --innodb-use-native-aio=0
